language: java
jdk:
  - openjdk11
services:
  - docker

branches:
  only:
    - "/^v[0-9]+\\.[0-9]+\\.[0-9]+.*$/"

install: true

before_script:
  - sudo chown -R $USER:$GROUP $TRAVIS_BUILD_DIR

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ "$TRAVIS_BRANCH" =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then cp ./src/devops/release.sh . && ./release.sh; fi
  - export TAG=$TRAVIS_BRANCH
  - export IMAGE_NAME='hygieiadoc/sonarcodequalitycollector'
  - echo $IMAGE_NAME
  - echo $TAG
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  - docker push $IMAGE_NAME

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/48597b0f75dd571734bc
    on_success: always
    on_failure: always
    on_start: always
  email:
    recipients:
      - tapabrata.pal@capitalone.com
      - ragha.vema@capitalone.com
      - hygieia2@capitalone.com
    on_success: always
    on_failure: always